apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: do65r58g7-go
  janus-idp.io/tekton: do65r58g7-go
  backstage.io/kubernetes-id: do65r58g7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: do65r58g7-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
